### ISSUE TITLE
users.removeTotp() no longer supported.

### ISSUE THREAD

**Issue by SLee9211** [keycloak/keycloak-nodejs-admin-client#147]
**Describe the bug**
I am writing a script to reset user OTPs, but it seems that users.removeTotp() is not working.  We are on Keycloak version 11.0.3 which I believed was supported by this library.

```
{
  error: 'RESTEASY003210: Could not find resource for full path: https://digitalu.info/auth/admin/realms/digital-university/users/543b0226-1065-4c54-b278-ba19008a74b1/remove-totp'
}
```

**To Reproduce**
1. API Call:  kcAdminClient.users.removeTotp({ id })
2. Returned with an error: 
    `error: 'RESTEASY003210: Could not find resource for full path: https://digitalu.info/auth/admin/realms/digital-university/users/543b0226-1065-4c54-b278-ba19008a74b1/remove-totp'`
3. ```
    try {
      await instance.users.removeTotp({ id: userObject.id });
      ...
    } catch (error) {
      console.log(error.response?.data, `-- ${JSON.stringify(userObject)}`);
    }
    ```

**Expected behavior**
I expect that the user's otp credentials would be removed successfully.

**Enviroment (please complete the following information):**
 - OS: macOS
 - Keycloak Version: 11.0.3
 - Library Version: 1.14.10

**Comment by ath88** [comment]
Unfortunately we don't have a good warning when there are single functions that are not supported for specific Keycloak version. In tests, the removeTotp-method is only being tested against Keycloak 7, since the endpoint has been removed from Keycloak 8. See https://github.com/keycloak/keycloak-nodejs-admin-client/pull/66/commits/48fd1f6fa9102058fb4ff89b90a7c1e2b8b80213.

I've opened https://github.com/keycloak/keycloak-nodejs-admin-client/issues/148 to discuss how we can fix this.
