### ISSUE TITLE
Poor CommonJS experience

### ISSUE THREAD

**Issue by claytongulick** [keycloak/keycloak-nodejs-admin-client#487]
### Describe the bug

Many projects don't have the option of switching wholesale over to ESM, and must use CommonJS. This will probably be true for the foreseeable future, as CommonJS will be here to stay for at least five years.

It's pretty difficult to tease out how to use this package with CommonJS, there are no docs or mention of it anywhere.

The best I can come up with to make it work is something like:

```
const module = await import('@keycloak/keycloak-admin-client');
const KcAdminClient = module.default.default;
```

I was only able to figure this out after putting breakpoints on and inspecting the module - it's strange to have to do .default.default

Is there a way to improve the developer experience with CommonJS?

### Version

18.0.0

**Comment by jonkoops** [comment]
Closing this as we landed pure ES module support in #381.

**Comment by alexagc** [comment]
@jonkoops, i would reconsider the distribution of commonjs module(following this rules https://nodejs.org/api/esm.html#esm_commonjs_namespaces), if only ships ESM modules this project force to move all code database of project to use ESM (or transpile code), this, even now, its not clear in nodejs core maintainers because commonjs its not going to be deprecate in a future and a large number of packages are still only in commonjs. Here its the personal recommendation of a nodejs maintainer (Matteo collina) about this topic: 

https://github.com/nodejs/node/issues/33954#issuecomment-924824456

**Comment by claytongulick** [comment]
> @jonkoops, i would reconsider the distribution of commonjs module(following this rules https://nodejs.org/api/esm.html#esm_commonjs_namespaces), if only ships ESM modules this project force to move all code database of project to use ESM (or transpile code), this, even now, its not clear in nodejs core maintainers because commonjs its not going to be deprecate in a future and a large number of packages are still only in commonjs. Here its the personal recommendation of a nodejs maintainer (Matteo collina) about this topic:
> 
> [nodejs/node#33954 (comment)](https://github.com/nodejs/node/issues/33954#issuecomment-924824456)

I agree, our solution for now is to move away from keycloak due to the response to this ticket and some other technical limitations.

I was disappointed with the response, it seemed needlessly strict, especially since packaging for bothe esm and cjs is pretty simple and a common practice.

**Comment by jonkoops** [comment]
> especially since packaging for both esm and cjs is pretty simple and a common practice.

No, [it's not](https://nodejs.org/api/packages.html#dual-package-hazard).

> if only ships ESM modules this project force to move all code database of project to use ESM

It doesn't force you to do this, you can still import ES modules from CommonJS. However there are caveats. You'll have to use the dynamic [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import), and since [top-level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await) is not supported in CommonJS you'll have to wrap your code in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE).

You can find more information about this in this [excellent blog post](https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples) by @adam-coster.

That said, I am a fervent [supporter](https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523#issuecomment-1222986081) of moving things to ESM, so my recommendation will always be to try to use it wherever possible.

**Comment by claytongulick** [comment]
> No, [it's not](https://nodejs.org/api/packages.html#dual-package-hazard).

Are you sure? https://antfu.me/posts/publish-esm-and-cjs

I've bundled for both without any major issues.
