### ISSUE TITLE
Error: "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by kevinswarner** [keycloak/keycloak-nodejs-admin-client#519]
### Describe the bug

We were using the old version of this library (e.g. keycloak-admin), but realized it is no longer supported. So we went to replace it with the newer @keycloak/keycloak-admin-client.

When I install the package, and then include it in one of my files like this...

```javascript
import KcAdminClient from '@keycloak/keycloak-admin-client';
```

I begin getting the following error when running my tests from Jest.

```
SyntaxError: Cannot use import statement outside a module

    > 1 | import KcAdminClient from '@keycloak/keycloak-admin-client';
        | ^
```

Jest has some suggestions, but it is unclear to me exactly why this is occurring. We are using Node 16.15.1.

I am assuming it has something to do with the way the @keycloak/keycloak-admin-client package is compiled when installed into my node_modules, but I really have no idea how to move forward.

Is there some help you can provide here? Thanks!

### Version

Latest version of @keycloak/keycloak-admin-client

**Comment by jonkoops** [comment]
You are using new JavaScript module syntax that is only supported when you enable it explicitly. For more information see the [Node.js documentation](https://nodejs.org/api/esm.html#enabling).

**Comment by kevinswarner** [comment]
I understand that, but what I am confused about is Jest is transforming my code, and I am using "import" throughout to import other third party packages, without any issues. It is ONLY this package that is causing the error. So there is something different about THIS package that I am trying to understand so that I can figure out how to use it.

**Comment by jonkoops** [comment]
The issue is likely that this package ships as a pure ESM library, without a CommonJS fallback. This is [an issue](https://github.com/facebook/jest/issues/9430) in Jest that still needs to be resolved.

You'll either have to enable ESM mode (see [documentation](https://jestjs.io/docs/ecmascript-modules)), or tweak `transformIgnorePatterns` so that this package is transformed by Jest (see https://github.com/facebook/jest/issues/11753#issuecomment-917917933).

**Comment by kevinswarner** [comment]
Thanks. The transformIgnorePatterns seemed to work, but then I had to add several more node modules to the list. But, it is working ok now. Is there a reason you are not providing a CommonJS fallback? Just curious.

**Comment by jonkoops** [comment]
CommonJS and ESM interoperability is notoriously hard, so we'd rather stick to a standardized solution that everyone will be using in the future.

**Comment by gadielkalleb** [comment]
"CommonJS and ESM interoperability is notoriously hard, so we'd rather stick to a standardized solution that everyone will be using in the future."

@jonkoops  it's not like that, the vast majority of people/companies that are using this package still follow type commonsJS.
this answer is a bit lazy (I say this with all due respect) but making a package like this available, changing it from one moment to another, and letting everyone manage to configure their projects is a bit of bad faith.

I say this because I'm having the same problem as @kevinswarner , and our product is in production and I can't downgrade it because version 18 has a vulnerability pointed out by our sonarqube and we can't update to version ^20.0.1 because it has this "problem" with ESM, complicated.

at least we managed to fork the project
