### ISSUE TITLE
kcAdminClient.roles.create should create composite roles

### ISSUE THREAD

**Issue by schuerg** [keycloak/keycloak-nodejs-admin-client#52]
**Describe the bug**
KcAdminClient should create a composite role if `composite=true` within the `RoleRepresentation` object.
And the roles defined in `composites` should be applied as associated roles.

**To Reproduce**
```ts
const realmRole = {
    name: 'manager',
    composite: true,
    composites: {
        realm: [
            'finance-manager',
        ]
    }
} as RoleRepresentation
await kcAdminClient.roles.create(realmRole)
```

**Expected behavior**
I expect a `manager` role to be present with the composite flag enabled.
And the `finance-manager` role to be a associated role of `manager`.

Instead only the `manager` role will be created as a non-composite role without association to the `finance-manager` role.

**Enviroment (please complete the following information):**
- OS: Fedora 31 (Workstation Edition)
- Node.js Version v12.16.1
- NPM Version 6.13.4
- TypeScript Version 3.8.3
- Keycloak Version 9.0.0
- keycloak-admin Library Version 1.13.0

**Comment by tvrg** [comment]
This seems to be already broken or not working by design in the keycloak REST API. At least I haven't managed to create a composite role with a single API call. Instead you first have to create a non-composite role and then explicitly add the composites using `POST /{realm}/clients/{id}/roles/{role-name}/composites`.
See https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_addcomposites

The same is true for the `GET`-API. `GET /{realm}/clients/{id}/roles/{role-name}/` returns the role without composites (but including the boolean flag `composite`). You have to use `GET /{realm}/clients/{id}/roles/{role-name}/composites` to get the composites.

Unfortunately it seems that the whole composites-API is missing from this nodejs client though.

**Comment by tvrg** [comment]
@zagaria I would like to implement new methods for the roles-composites API as I need them for my current project. Please let me know if a corresponding PR would be welcome.

**Comment by edewit** [comment]
added this with #95
